import { contextBridge, ipcRenderer } from "electron";
import type { ElectronAPI } from "./types";

const api: ElectronAPI = {
  getPlugins: () => ipcRenderer.invoke("get-plugins"),
  getLocalItems: (directory) => ipcRenderer.invoke("get-local-items", directory),
  getMcpServers: (directory) => ipcRenderer.invoke("get-mcp-servers", directory),
  getProfiles: () => ipcRenderer.invoke("get-profiles"),
  createProfile: (profile) => ipcRenderer.invoke("create-profile", profile),
  updateProfile: (profile) => ipcRenderer.invoke("update-profile", profile),
  renameProfile: (oldName, profile) => ipcRenderer.invoke("rename-profile", oldName, profile),
  deleteProfile: (name) => ipcRenderer.invoke("delete-profile", name),
  duplicateProfile: (name) => ipcRenderer.invoke("duplicate-profile", name),
  launchProfile: (name, directory) =>
    ipcRenderer.invoke("launch-profile", name, directory),
  checkProfileHealth: () => ipcRenderer.invoke("check-profile-health"),
  selectDirectory: () => ipcRenderer.invoke("select-directory"),
  isBinInPath: () => ipcRenderer.invoke("is-bin-in-path"),
  addBinToPath: () => ipcRenderer.invoke("add-bin-to-path"),
  ensureDefaultProfile: () => ipcRenderer.invoke("ensure-default-profile"),
  updatePlugin: (name) => ipcRenderer.invoke("update-plugin", name),
  uninstallPlugin: (name) => ipcRenderer.invoke("uninstall-plugin", name),
  checkPluginUpdates: () => ipcRenderer.invoke("check-plugin-updates"),
  getAvailablePlugins: () => ipcRenderer.invoke("get-available-plugins"),
  installPlugin: (pluginId: string) => ipcRenderer.invoke("install-plugin", pluginId),
  addMarketplace: (source) => ipcRenderer.invoke("add-marketplace", source),
  removeMarketplace: (name) => ipcRenderer.invoke("remove-marketplace", name),
  listMarketplaces: () => ipcRenderer.invoke("list-marketplaces"),
  getAnalytics: (since, project) => ipcRenderer.invoke("get-analytics", since, project),
  getActiveSessions: () => ipcRenderer.invoke("get-active-sessions"),
  checkForAppUpdate: () => ipcRenderer.invoke("check-for-app-update"),
  getTeams: () => ipcRenderer.invoke("get-teams"),
  saveTeam: (team) => ipcRenderer.invoke("save-team", team),
  deleteTeam: (name) => ipcRenderer.invoke("delete-team", name),
  renameTeam: (oldName, team) => ipcRenderer.invoke("rename-team", oldName, team),
  getTeamMergePreview: (team) => ipcRenderer.invoke("get-team-merge-preview", team),
  checkTeamHealth: () => ipcRenderer.invoke("check-team-health"),
  launchTeam: (team, directory) => ipcRenderer.invoke("launch-team", team, directory),
  launchTeamWithOptions: (team, directory, options) => ipcRenderer.invoke("launch-team-with-options", team, directory, options),
  launchProfileWithOptions: (name, directory, options) => ipcRenderer.invoke("launch-profile-with-options", name, directory, options),
  checkTmuxInstalled: () => ipcRenderer.invoke("check-tmux-installed"),
  // Global settings
  getGlobalClaudeMd: () => ipcRenderer.invoke("get-global-claude-md"),
  saveGlobalClaudeMd: (content) => ipcRenderer.invoke("save-global-claude-md", content),
  getPrompts: () => ipcRenderer.invoke("get-prompts"),
  savePrompts: (prompts) => ipcRenderer.invoke("save-prompts", prompts),
  exportPrompt: (prompt) => ipcRenderer.invoke("export-prompt", prompt),
  importPrompt: () => ipcRenderer.invoke("import-prompt"),
  checkCredentialStatus: () => ipcRenderer.invoke("check-credential-status"),
  runDiagnostics: () => ipcRenderer.invoke("run-diagnostics"),
  getAppPreferences: () => ipcRenderer.invoke("get-app-preferences"),
  saveAppPreferences: (prefs) => ipcRenderer.invoke("save-app-preferences", prefs),
  getGlobalEnv: () => ipcRenderer.invoke("get-global-env"),
  saveGlobalEnv: (env) => ipcRenderer.invoke("save-global-env", env),
  getGlobalHooks: () => ipcRenderer.invoke("get-global-hooks"),
  saveGlobalHooks: (hooks) => ipcRenderer.invoke("save-global-hooks", hooks),
  getGlobalDefaults: () => ipcRenderer.invoke("get-global-defaults"),
  saveGlobalDefaults: (defaults) => ipcRenderer.invoke("save-global-defaults", defaults),
  // Projects
  getImportedProjects: () => ipcRenderer.invoke("get-imported-projects"),
  addImportedProject: (dir) => ipcRenderer.invoke("add-imported-project", dir),
  removeImportedProject: (dir) => ipcRenderer.invoke("remove-imported-project", dir),
  getProjectClaudeMd: (dir) => ipcRenderer.invoke("get-project-claude-md", dir),
  saveProjectClaudeMd: (dir, content) => ipcRenderer.invoke("save-project-claude-md", dir, content),
  readProjectFile: (dir, relativePath) => ipcRenderer.invoke("read-project-file", dir, relativePath),
  writeProjectFile: (dir, relativePath, content) => ipcRenderer.invoke("write-project-file", dir, relativePath, content),
  deleteProjectFile: (dir, relativePath) => ipcRenderer.invoke("delete-project-file", dir, relativePath),
  getProjectMcpConfig: (dir) => ipcRenderer.invoke("get-project-mcp-config", dir),
  saveProjectMcpConfig: (dir, servers) => ipcRenderer.invoke("save-project-mcp-config", dir, servers),
  getProjectSettings: (dir) => ipcRenderer.invoke("get-project-settings", dir),
  saveProjectSettings: (dir, settings) => ipcRenderer.invoke("save-project-settings", dir, settings),
  getGitContext: (dir) => ipcRenderer.invoke("get-git-context", dir),
  openInFinder: (path) => ipcRenderer.invoke("open-in-finder", path),
  revealInFinder: (path) => ipcRenderer.invoke("reveal-in-finder", path),
  openExternalUrl: (url) => ipcRenderer.invoke("open-external-url", url),
  getProfileConfigDir: (name) => ipcRenderer.invoke("get-profile-config-dir", name),
  getClaudeHome: () => ipcRenderer.invoke("get-claude-home"),
  getCuratedMarketplace: () => ipcRenderer.invoke("get-curated-marketplace"),
  refreshCuratedMarketplace: () => ipcRenderer.invoke("refresh-curated-marketplace"),
  fetchUpstreamMarketplace: (source) => ipcRenderer.invoke("fetch-upstream-marketplace", source),
  fetchPluginItems: (source, pluginPath) => ipcRenderer.invoke("fetch-plugin-items", source, pluginPath),
  fetchRepoReadme: (source) => ipcRenderer.invoke("fetch-repo-readme", source),
};

contextBridge.exposeInMainWorld("api", api);
